### ISSUE TITLE
just sharing error we received with this my.cnf file

### ISSUE THREAD

**Issue by seansan** [magenx/magento-mysql#2]
just sharing error we received with this my.cnf file

hope it helps

We had to remove these two settings:
innodb_log_files_in_group = 2
innodb_log_file_size = 256M

Errors
Starting MySQL.. ERROR! The server quit without updating PID file (/var/lib/mysql/server.com.pid).

150209 15:53:10 InnoDB: Completed initialization of buffer pool
InnoDB: Error: log file ./ib_logfile0 is of different size 0 5242880 bytes
InnoDB: than specified in the .cnf file 0 268435456 bytes!

 [Warning] option 'slow_query_log': boolean value '/var/log/mysql/slow-queries.log' wasn't recognized. Set to OFF.

**Comment by magenx** [comment]
you must not remove those options, instead you need to delete your log files, and use proper log size configured in mysql options file, depends on your data and workload size...
