### ISSUE TITLE
Question about msyql Settings.

### ISSUE THREAD

**Issue by danielc1234** [magenx/Magento-mysql#3]
Hi,

I happened to find your customized settings for my.cnf and was wondering if they would work on a server running more than one installation of Magento?

We have around 4 installs and one is a multi-store.
We are using the latest version of mysql and perona. 

I would love to try your settings, but was hoping you could enlighten me on your suggestions.

Thanks
Daniel

**Comment by magenx** [comment]
you need to optimize it anyway according to your workload using some mysqltuner. no matter how many shops you have.

**Comment by danielc1234** [comment]
Thanks, I will look into the mysqltuner. Will it help in the way of recommendations on optimization or just functionality?
